import { Hono, type Context } from 'hono';
import type { Env } from '../index.js';
import { calculateCafeAvailability, validateBookingWindow, MockGateProvider } from '../services/cafe-domain.js';

const cafe = new Hono<Env>();
type Json = Record<string, unknown>;
const ok = <T>(data: T) => ({ success: true as const, data });
const fail = (code: string, message: string, details?: unknown) => ({ success: false as const, error: { code, message, ...(details === undefined ? {} : { details }) } });
const enc = new TextEncoder();
const b64 = (bytes: Uint8Array) => btoa(String.fromCharCode(...bytes)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
async function hash(value: string) { return b64(new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(value)))); }
async function hmac(value:string, secret:string) { const key=await crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']); return b64(new Uint8Array(await crypto.subtle.sign('HMAC',key,enc.encode(value)))); }
async function sessionToken(friendId:string, accountId:string, secret:string) { const payload=b64(enc.encode(JSON.stringify({friendId,accountId,exp:Date.now()+3_600_000}))); return `${payload}.${await hmac(payload,secret)}`; }
async function owner(c:Context<Env>) { const token=c.req.header('X-Cafe-Session') ?? ''; const [payload,sig]=token.split('.'); if(!payload||!sig||sig!==await hmac(payload,c.env.CAFE_SESSION_SECRET ?? c.env.API_KEY)) return null; try { const data=JSON.parse(atob(payload.replace(/-/g,'+').replace(/_/g,'/'))) as {friendId:string;accountId:string;exp:number}; return data.exp>Date.now()?data:null; } catch { return null; } }
function bodyObject(value:unknown): value is Json { return Boolean(value) && typeof value==='object' && !Array.isArray(value); }

cafe.post('/api/liff/session', async c => {
  const body=await c.req.json().catch(()=>null); if(!bodyObject(body)||typeof body.idToken!=='string'||typeof body.liffId!=='string') return c.json(fail('INVALID_INPUT','缺少 LINE ID Token 或 LIFF ID'),400);
  const account=await c.env.DB.prepare('SELECT id, login_channel_id FROM line_accounts WHERE liff_id=? AND is_active=1').bind(body.liffId).first<{id:string;login_channel_id:string|null}>();
  if(!account) return c.json(fail('UNAUTHORIZED','無法識別 LIFF 應用程式'),401);
  const channelId=account.login_channel_id ?? c.env.LINE_LOGIN_CHANNEL_ID;
  const verify=await fetch('https://api.line.me/oauth2/v2.1/verify',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({id_token:body.idToken,client_id:channelId})});
  if(!verify.ok) return c.json(fail('UNAUTHORIZED','LINE 登入驗證失敗'),401);
  const profile=await verify.json<{sub?:string;name?:string}>(); if(!profile.sub) return c.json(fail('UNAUTHORIZED','LINE Token 缺少使用者識別'),401);
  let friend=await c.env.DB.prepare('SELECT id FROM friends WHERE line_user_id=? AND line_account_id=?').bind(profile.sub,account.id).first<{id:string}>();
  if(!friend){ const id=crypto.randomUUID(); await c.env.DB.prepare(`INSERT INTO friends(id,line_user_id,line_account_id,display_name,is_following,created_at,updated_at) VALUES(?,?,?,?,0,datetime('now'),datetime('now'))`).bind(id,profile.sub,account.id,profile.name??'LINE 使用者').run(); friend={id}; }
  return c.json(ok({sessionToken:await sessionToken(friend.id,account.id,c.env.CAFE_SESSION_SECRET??c.env.API_KEY),expiresIn:3600}));
});

cafe.get('/api/cafe/venues', async c => { const rows=await c.env.DB.prepare(`SELECT id,line_account_id AS lineAccountId,name,slug,description,address,timezone FROM venues WHERE is_active=1 ORDER BY name`).all(); return c.json(ok(rows.results)); });
cafe.get('/api/cafe/spaces', async c => { const venue=c.req.query('venueId'); if(!venue)return c.json(fail('INVALID_INPUT','缺少 venueId'),400); const rows=await c.env.DB.prepare(`SELECT id,venue_id AS venueId,name,code,description,booking_mode AS bookingMode,capacity_total AS capacityTotal,slot_interval_minutes AS slotIntervalMinutes,minimum_duration_minutes AS minimumDurationMinutes,maximum_duration_minutes AS maximumDurationMinutes,advance_booking_minutes AS advanceBookingMinutes,max_advance_days AS maxAdvanceDays,cancel_before_minutes AS cancelBeforeMinutes,base_price AS basePrice,currency FROM spaces WHERE venue_id=? AND is_active=1 ORDER BY sort_order`).bind(venue).all(); return c.json(ok(rows.results)); });

async function availability(c:Context<Env>) {
  const spaceId=c.req.query('spaceId')??''; const date=c.req.query('date')??''; const start=c.req.query('startTime')??''; const duration=Number(c.req.query('durationMinutes')); const quantity=Number(c.req.query('quantity')??1);
  const space=await c.env.DB.prepare(`SELECT *,v.timezone FROM spaces s JOIN venues v ON v.id=s.venue_id WHERE s.id=? AND s.is_active=1`).bind(spaceId).first<any>(); if(!space)return {error:c.json(fail('SPACE_NOT_FOUND','找不到指定空間'),404)};
  if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!/^\d{2}:\d{2}$/.test(start)||!Number.isInteger(duration)||!Number.isInteger(quantity)||quantity<1)return {error:c.json(fail('INVALID_DURATION','日期、時段、使用時間或人數格式錯誤'),400)};
  const startsAt=new Date(`${date}T${start}:00+08:00`), endsAt=new Date(startsAt.getTime()+duration*60_000), now=new Date();
  const windowError=validateBookingWindow({startsAt,endsAt,now,minimumDurationMinutes:space.minimum_duration_minutes,maximumDurationMinutes:space.maximum_duration_minutes,slotIntervalMinutes:space.slot_interval_minutes,advanceBookingMinutes:space.advance_booking_minutes,maxAdvanceDays:space.max_advance_days}); if(windowError)return {error:c.json(fail(windowError,windowError==='INVALID_DURATION'?'使用時間不符合空間規則':'預約日期不在開放範圍'),400)};
  const weekday=new Date(`${date}T12:00:00+08:00`).getUTCDay(); const opening=await c.env.DB.prepare(`SELECT 1 FROM space_opening_hours WHERE space_id=? AND day_of_week=? AND is_active=1 AND start_time<=? AND end_time>=?`).bind(spaceId,weekday,start,endsAt.toLocaleTimeString('en-GB',{timeZone:'Asia/Taipei',hour:'2-digit',minute:'2-digit'})).first(); if(!opening)return {error:c.json(fail('OUTSIDE_OPENING_HOURS','此時段不在營業時間內'),409)};
  const blackout=await c.env.DB.prepare(`SELECT reason FROM space_blackouts WHERE space_id=? AND starts_at<? AND ends_at>? LIMIT 1`).bind(spaceId,endsAt.toISOString(),startsAt.toISOString()).first<{reason:string}>(); if(blackout)return {error:c.json(fail('OUTSIDE_OPENING_HOURS','此時段因休館、清潔或維修暫停預約',{reason:blackout.reason}),409)};
  const bookings=await c.env.DB.prepare(`SELECT id,starts_at AS startsAt,ends_at AS endsAt,quantity,status,hold_expires_at AS holdExpiresAt FROM cafe_bookings WHERE space_id=? AND starts_at<? AND ends_at>?`).bind(spaceId,endsAt.toISOString(),startsAt.toISOString()).all<any>();
  const units=await c.env.DB.prepare(`SELECT id FROM space_units WHERE space_id=? AND is_active=1 ORDER BY sort_order`).bind(spaceId).all<{id:string}>();
  const allocations=await c.env.DB.prepare(`SELECT a.booking_id,a.space_unit_id FROM booking_unit_allocations a JOIN cafe_bookings b ON b.id=a.booking_id WHERE b.space_id=? AND a.allocation_status IN ('held','reserved') AND a.slot_start<? AND a.slot_end>?`).bind(spaceId,endsAt.toISOString(),startsAt.toISOString()).all<{booking_id:string;space_unit_id:string}>();
  const result=calculateCafeAvailability({startsAt:startsAt.toISOString(),endsAt:endsAt.toISOString(),quantity,capacityTotal:space.capacity_total,bookingMode:space.booking_mode,unitIds:units.results.map(x=>x.id),reservations:bookings.results.map((b:any)=>({...b,unitIds:allocations.results.filter(a=>a.booking_id===b.id).map(a=>a.space_unit_id)})),now:now.toISOString()});
  return {space,startsAt,endsAt,result};
}
cafe.get('/api/cafe/availability',async c=>{const value=await availability(c);return 'error'in value?value.error:c.json(ok(value.result));});

cafe.post('/api/cafe/booking-holds',async c=>createBooking(c,'holding'));
cafe.post('/api/cafe/bookings',async c=>createBooking(c,'confirmed'));
async function createBooking(c:Context<Env>,status:'holding'|'confirmed') {
  const who=await owner(c); if(!who)return c.json(fail('UNAUTHORIZED','請先以 LINE 登入'),401); const body=await c.req.json().catch(()=>null); if(!bodyObject(body))return c.json(fail('INVALID_INPUT','請求格式錯誤'),400);
  const key=c.req.header('Idempotency-Key'); if(!key)return c.json(fail('INVALID_INPUT','缺少 Idempotency-Key'),400);
  const prior=await c.env.DB.prepare('SELECT response_body FROM cafe_idempotency_keys WHERE key=? AND friend_id=?').bind(key,who.friendId).first<{response_body:string|null}>(); if(prior?.response_body)return c.json(JSON.parse(prior.response_body));
  const params=new URLSearchParams({spaceId:String(body.spaceId??''),date:String(body.date??''),startTime:String(body.startTime??''),durationMinutes:String(body.durationMinutes??''),quantity:String(body.quantity??1)}); const request=new Request(`${c.req.url.split('?')[0]}?${params}`); const proxy=Object.create(c) as Context<Env>; Object.defineProperty(proxy,'req',{value:{...c.req,query:(name:string)=>new URL(request.url).searchParams.get(name)??undefined}});
  const value=await availability(proxy); if('error'in value)return value.error; if(!value.result.available)return c.json(fail('INSUFFICIENT_CAPACITY','剩餘座位不足，請調整人數或時段',value.result),409);
  if(typeof body.customerName!=='string'||typeof body.customerPhone!=='string'||body.termsAccepted!==true)return c.json(fail('INVALID_INPUT','請填寫姓名、手機並同意使用規則'),400);
  const id=crypto.randomUUID(),now=new Date().toISOString(),hold=status==='holding'?new Date(Date.now()+10*60_000).toISOString():null, code=`ER${Date.now().toString(36).toUpperCase()}`; const selected=Array.isArray(body.unitIds)?body.unitIds.map(String):value.result.availableUnitIds?.slice(0,Number(body.quantity))??[]; const units=value.space.booking_mode==='capacity_pool'?(await c.env.DB.prepare(`SELECT id FROM space_units WHERE space_id=? AND is_active=1 AND id NOT IN (SELECT space_unit_id FROM booking_unit_allocations WHERE allocation_status IN ('held','reserved') AND slot_start<? AND slot_end>?) LIMIT ?`).bind(body.spaceId,value.endsAt.toISOString(),value.startsAt.toISOString(),Number(body.quantity)).all<{id:string}>()).results.map(x=>x.id):selected;
  if(units.length<Number(body.quantity))return c.json(fail('INSUFFICIENT_CAPACITY','座位剛被其他使用者預約，請重新選擇'),409);
  const bookingStmt=c.env.DB.prepare(`INSERT INTO cafe_bookings(id,booking_code,line_account_id,friend_id,venue_id,space_id,starts_at,ends_at,quantity,status,hold_expires_at,payment_status,price_at_booking,currency,customer_name,customer_phone,terms_version,source,confirmed_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(id,code,who.accountId,who.friendId,value.space.venue_id,body.spaceId,value.startsAt.toISOString(),value.endsAt.toISOString(),Number(body.quantity),status,hold,'not_required',value.space.base_price*Number(body.quantity),value.space.currency,body.customerName,body.customerPhone,'2026-07-28','liff',status==='confirmed'?now:null,now,now);
  const allocationStmts=units.map((unitId:string)=>c.env.DB.prepare(`INSERT INTO booking_unit_allocations(id,booking_id,space_unit_id,slot_start,slot_end,allocation_status,expires_at,created_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT DO NOTHING`).bind(crypto.randomUUID(),id,unitId,value.startsAt.toISOString(),value.endsAt.toISOString(),status==='holding'?'held':'reserved',hold,now));
  const response=ok({id,bookingCode:code,status,startsAt:value.startsAt.toISOString(),endsAt:value.endsAt.toISOString(),quantity:Number(body.quantity),unitIds:units}); const hashValue=await hash(JSON.stringify(body));
  try { await c.env.DB.batch([bookingStmt,...allocationStmts,c.env.DB.prepare(`INSERT INTO booking_events VALUES(?,?,?,?,?,?,?,?,?)`).bind(crypto.randomUUID(),id,status==='holding'?'hold_created':'confirmed','customer',who.friendId,null,status,null,now),c.env.DB.prepare(`INSERT INTO cafe_idempotency_keys VALUES(?,?,?,?,?,?,?,?)`).bind(key,who.friendId,hashValue,200,JSON.stringify(response),id,now,new Date(Date.now()+86400000).toISOString())]); } catch { return c.json(fail('INSUFFICIENT_CAPACITY','座位剛被其他使用者預約，請重新查詢'),409); }
  return c.json(response,status==='holding'?201:200);
}

cafe.get('/api/cafe/me/bookings',async c=>{const who=await owner(c);if(!who)return c.json(fail('UNAUTHORIZED','請先登入'),401);const rows=await c.env.DB.prepare(`SELECT b.*,s.name AS space_name FROM cafe_bookings b JOIN spaces s ON s.id=b.space_id WHERE b.friend_id=? ORDER BY b.starts_at DESC`).bind(who.friendId).all();return c.json(ok(rows.results));});
cafe.get('/api/cafe/me/bookings/:id',async c=>{const who=await owner(c);if(!who)return c.json(fail('UNAUTHORIZED','請先登入'),401);const row=await c.env.DB.prepare(`SELECT b.*,s.name AS space_name FROM cafe_bookings b JOIN spaces s ON s.id=b.space_id WHERE b.id=? AND b.friend_id=?`).bind(c.req.param('id'),who.friendId).first();return row?c.json(ok(row)):c.json(fail('BOOKING_NOT_FOUND','找不到預約'),404);});
cafe.post('/api/cafe/bookings/:id/cancel',async c=>{const who=await owner(c);if(!who)return c.json(fail('UNAUTHORIZED','請先登入'),401);const row=await c.env.DB.prepare(`SELECT * FROM cafe_bookings WHERE id=? AND friend_id=?`).bind(c.req.param('id'),who.friendId).first<any>();if(!row)return c.json(fail('BOOKING_NOT_FOUND','找不到預約'),404);if(row.status==='cancelled')return c.json(ok({id:row.id,status:'cancelled'}));const space=await c.env.DB.prepare(`SELECT cancel_before_minutes FROM spaces WHERE id=?`).bind(row.space_id).first<any>();if(new Date(row.starts_at).getTime()-Date.now()<(space?.cancel_before_minutes??2880)*60000)return c.json(fail('BOOKING_NOT_CANCELLABLE','已超過自行取消期限，請聯絡客服'),409);const now=new Date().toISOString();await c.env.DB.batch([c.env.DB.prepare(`UPDATE cafe_bookings SET status='cancelled',cancelled_at=?,updated_at=? WHERE id=?`).bind(now,now,row.id),c.env.DB.prepare(`DELETE FROM booking_unit_allocations WHERE booking_id=?`).bind(row.id),c.env.DB.prepare(`INSERT INTO booking_events VALUES(?,?,?,?,?,?,?,?,?)`).bind(crypto.randomUUID(),row.id,'cancelled_by_customer','customer',who.friendId,row.status,'cancelled',null,now)]);return c.json(ok({id:row.id,status:'cancelled'}));});
cafe.get('/api/cafe/bookings/:id/access-credential',async c=>{const who=await owner(c);if(!who)return c.json(fail('UNAUTHORIZED','請先登入'),401);const row=await c.env.DB.prepare(`SELECT b.*,s.early_entry_minutes,s.late_exit_minutes,s.qr_display_before_minutes FROM cafe_bookings b JOIN spaces s ON s.id=b.space_id WHERE b.id=? AND b.friend_id=?`).bind(c.req.param('id'),who.friendId).first<any>();if(!row)return c.json(fail('BOOKING_NOT_FOUND','找不到預約'),404);if(c.env.CAFE_MOCK_GATE!=='true')return c.json(ok({enabled:false,message:'入場 QR Code 將於功能啟用後提供'}));return c.json(ok({enabled:true,availableFrom:new Date(new Date(row.starts_at).getTime()-row.qr_display_before_minutes*60000).toISOString(),message:'測試模式已啟用'}));});

cafe.get('/api/admin/cafe/overview',async c=>{const now=new Date(),end=new Date(now.getTime()+86400000);const stats=await c.env.DB.prepare(`SELECT COALESCE(SUM(CASE WHEN status='checked_in' THEN quantity ELSE 0 END),0) AS inside,COALESCE(SUM(CASE WHEN created_at>=? THEN quantity ELSE 0 END),0) AS bookedToday,COALESCE(SUM(CASE WHEN checked_in_at>=? THEN quantity ELSE 0 END),0) AS checkinsToday,COALESCE(SUM(CASE WHEN status='cancelled' AND cancelled_at>=? THEN quantity ELSE 0 END),0) AS cancelledToday,COALESCE(SUM(CASE WHEN status='no_show' AND updated_at>=? THEN quantity ELSE 0 END),0) AS noShowsToday,COALESCE(SUM(CASE WHEN status='confirmed' AND starts_at>=? AND starts_at<? THEN quantity ELSE 0 END),0) AS arrivingSoon FROM cafe_bookings`).bind(now.toISOString().slice(0,10),now.toISOString().slice(0,10),now.toISOString().slice(0,10),now.toISOString().slice(0,10),now.toISOString(),end.toISOString()).first();const spaces=await c.env.DB.prepare(`SELECT id,name,capacity_total AS capacityTotal FROM spaces WHERE is_active=1 ORDER BY sort_order`).all();const upcoming=await c.env.DB.prepare(`SELECT b.booking_code AS bookingCode,b.customer_name AS customerName,b.customer_phone AS customerPhone,b.starts_at AS startsAt,b.ends_at AS endsAt,b.quantity,b.status,s.name AS spaceName FROM cafe_bookings b JOIN spaces s ON s.id=b.space_id WHERE b.starts_at>=? AND b.starts_at<? ORDER BY b.starts_at LIMIT 50`).bind(now.toISOString(),end.toISOString()).all();return c.json(ok({stats,spaces:spaces.results,upcoming:upcoming.results}));});
cafe.get('/api/admin/cafe/bookings',async c=>{const q=c.req.query('q')??'';const rows=await c.env.DB.prepare(`SELECT b.id,b.booking_code AS bookingCode,b.customer_name AS customerName,b.customer_phone AS customerPhone,b.starts_at AS startsAt,b.ends_at AS endsAt,b.quantity,b.status,b.payment_status AS paymentStatus,b.checked_in_at AS checkedInAt,b.created_at AS createdAt,s.name AS spaceName,f.display_name AS lineDisplayName FROM cafe_bookings b JOIN spaces s ON s.id=b.space_id JOIN friends f ON f.id=b.friend_id WHERE (?='' OR b.booking_code LIKE ? OR b.customer_name LIKE ? OR b.customer_phone LIKE ?) ORDER BY b.starts_at DESC LIMIT 200`).bind(q,`%${q}%`,`%${q}%`,`%${q}%`).all();return c.json(ok(rows.results));});

cafe.post('/api/gate/v1/scan',async c=>{const body=await c.req.json().catch(()=>null);if(!bodyObject(body)||typeof body.deviceCode!=='string'||typeof body.qrToken!=='string')return c.json(fail('INVALID_INPUT','掃描資料格式錯誤'),400);const device=await c.env.DB.prepare(`SELECT * FROM gate_devices WHERE device_code=? AND is_active=1`).bind(body.deviceCode).first<any>();const key=c.req.header('X-Gate-Device-Key')??'';if(!device||await hash(key)!==device.device_key_hash)return c.json(ok({decision:'deny',reason:'DEVICE_NOT_ALLOWED'}));if(c.env.CAFE_MOCK_GATE!=='true')return c.json(ok({decision:'deny',reason:'DEVICE_NOT_ALLOWED'}));const provider=new MockGateProvider();const result=await provider.unlock({deviceCode:body.deviceCode,bookingId:'mock',requestId:crypto.randomUUID()});return c.json(ok(result.success?{decision:'allow',bookingId:'mock',action:'unlock',validUntil:new Date(Date.now()+60000).toISOString()}:{decision:'deny',reason:'DEVICE_NOT_ALLOWED'}));});

export default cafe;
